<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Vendor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Ambil ID Categories
        $categories = Category::pluck('id', 'name')->toArray();

        // 2. Ambil ID Vendors
        $vendors = Vendor::pluck('id', 'name')->toArray();

        // 3. Data Produk dari Excel + Deskripsi Dummy Teknis
        $productsData = [
            // --- VALVE ---
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '076DH',
                'name'          => 'Solenoid Valve 24VAC 1"',
                'description'   => 'Katup solenoid listrik ukuran 1 inci bertenaga 24VAC untuk mengontrol aliran air irigasi secara otomatis via timer/controller. Tahan tekanan sedang.',
                'photo'         => 'products/076DH.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '101DH',
                'name'          => 'Solenoid Valve 24VAC 1"',
                'description'   => 'Katup solenoid otomatis 1 inci tugas berat (heavy-duty) bertenaga 24VAC. Dilengkapi tuas manual override dan diafragma presisi.',
                'photo'         => 'products/101DH.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '151DH',
                'name'          => 'Solenoid Valve 24VAC 1-½"',
                'description'   => 'Katup kontrol otomatis 1.5 inci bertenaga 24VAC. Ideal untuk instalasi blok irigasi skala menengah pada lahan pertanian dan kebun.',
                'photo'         => 'products/151DH.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '201BM',
                'name'          => 'Solenoid Valve 24VAC 2"',
                'description'   => 'Katup solenoid 2 inci kapasitas debit besar. Dibuat dari material plastik rekayasa anti-korosi dan tahan sinar UV.',
                'photo'         => 'products/201BM.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '301BM',
                'name'          => 'Solenoid Valve 24VAC 3"',
                'description'   => 'Katup solenoid industri 3 inci untuk zona irigasi perkebunan besar. Mengatur bukaan air debit tinggi dengan transisi halus.',
                'photo'         => 'products/301BM.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '151T',
                'name'          => 'Manual Pressure Reducing Valve 1-½"',
                'description'   => 'Katup penurun tekanan manual ukuran 1.5 inci. Berfungsi menstabilkan tekanan air sebelum masuk ke saluran drip atau sprinkler.',
                'photo'         => 'products/151T.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '201T',
                'name'          => 'Manual Pressure Reducing Valve 2"',
                'description'   => 'Katup peredam tekanan manual 2 inci untuk melindungi pipa dan emiter dari lonjakan tekanan pompa irigasi.',
                'photo'         => 'products/201T.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '301T',
                'name'          => 'Manual Pressure Reducing Valve 3"',
                'description'   => 'Katup pengatur tekanan manual 3 inci skala besar. Memastikan distribusi tekanan seimbang pada seluruh jaringan irigasi utama.',
                'photo'         => 'products/301T.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '151TD',
                'name'          => 'Pressure Reducing Solenoid Valve 1-1/2" 24VAC',
                'description'   => 'Kombinasi katup solenoid 1.5 inci 24VAC dan pengatur tekanan otomatis. Membuka aliran sekaligus menstabilkan tekanan air.',
                'photo'         => 'products/151TD.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '201TD',
                'name'          => 'Pressure Reducing Solenoid Valve 2" 24VAC',
                'description'   => 'Katup solenoid 2 inci dengan fitur pengatur tekanan bawaan. Sangat cocok untuk fertigasi presisi pada greenhouse.',
                'photo'         => 'products/201TD.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '301TD',
                'name'          => 'Pressure Reducing Solenoid Valve 3" 24VAC',
                'description'   => 'Katup kombinasi solenoid dan penstabil tekanan 3 inci untuk sistem irigasi komersial bertekanan variabel.',
                'photo'         => 'products/301TD.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '201X',
                'name'          => 'Pressure Relief Valve 2"',
                'description'   => 'Katup pengaman tekanan (Relief Valve) 2 inci. Otomatis membuang kelebihan tekanan pipa untuk mencegah pipa pecah.',
                'photo'         => 'products/201X.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Yuyao Zanchen Auto.Contrl',
                'code'          => '301X',
                'name'          => 'Pressure Relief Valve 3"',
                'description'   => 'Katup pelepas tekanan berlebih ukuran 3 inci. Melindungi infrastruktur jaringan utama irigasi dari bahaya water hammer.',
                'photo'         => 'products/301X.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'KAV0320B',
                'name'          => 'Kinetic Air Release Valve ¾" model-G',
                'description'   => 'Katup pelepas udara kinetik ukuran 3/4 inci. Membuang jebakan udara dalam pipa saat pompa menyala dan mencegah kevacuman saat mati.',
                'photo'         => 'products/KAV0320B.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'KA-11-25',
                'name'          => 'Kinetic Air Release Valve ¾" model C21',
                'description'   => 'Air Release Valve 3/4 inci model C21. Desain ringkas anti-tersumbat untuk kelancaran aliran air tanpa hambatan gelembung udara.',
                'photo'         => 'products/KA-11-25.webp',
            ],
            [
                'category_name' => 'Valve',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'KA-11-32',
                'name'          => 'Kinetic Air Release Valve 1" model C21',
                'description'   => 'Air Valve kinetik ukuran 1 inci. Menjaga efisiensi sistem perpipaan dengan membuang udara terperangkap secara kontinyu.',
                'photo'         => 'products/KA-11-32.webp',
            ],

            // --- FILTER ---
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F32YS',
                'name'          => 'Screen Filter Y-type 130 micron 1" , max.6 m³/h',
                'description'   => 'Filter saringan kawat (screen) Y-type 1 inci kelir 130 micron. Mencegah kotoran fisik dan pasir menyumbat dripper.',
                'photo'         => 'products/F32YS.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F50YS',
                'name'          => 'Screen Filter Y-type 130 micron 1-½" , max. 14m³/h',
                'description'   => 'Saringan irigasi model Y ukuran 1.5 inci. Efektif menyaring partikel hingga 130 micron pada debit air maksimal 14 m³/jam.',
                'photo'         => 'products/F50YS.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F63YS',
                'name'          => 'Screen Filter Y-type 130 micron 2" , max.25m³/h',
                'description'   => 'Filter screen Y 2 inci debit 25 m³/jam. Didesain untuk pembersihan elemen penyaring yang mudah dan cepat.',
                'photo'         => 'products/F63YS.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F90YS',
                'name'          => 'Screen Filter Y-type 130 micron 3" , max.35m³/h',
                'description'   => 'Filter penyaring fisik kotoran air 3 inci. Cocok untuk sumber air bersih/sumur bor skala kebun luas.',
                'photo'         => 'products/F90YS.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F32YD',
                'name'          => 'Disc Filter Y-type 130 micron 1", max. 6m³/h',
                'description'   => 'Filter piringan (disc) Y 1 inci 130 micron. Sangat ampuh menyaring lumut dan bahan organik halus dibanding screen filter.',
                'photo'         => 'products/F32YD.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F50YD',
                'name'          => 'Disc Filter Y-type 130 micron 1-½", max.14m³/h',
                'description'   => 'Filter disc Y-type 1.5 inci 130 micron. Tahan korosi kimia pupuk cair pada sistem fertigasi pertanian.',
                'photo'         => 'products/F50YD.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F63YD',
                'name'          => 'Disc Filter Y-type 130 micron 2", max.25m³/h',
                'description'   => 'Filter piringan penyaring pasir & organik 2 inci. Menjamin kebersihan air untuk emiter micro-sprinkler.',
                'photo'         => 'products/F63YD.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F90YD',
                'name'          => 'Disc Filter Y-type 130 micron 3", max.35m³/h',
                'description'   => 'Filter disc Y 3 inci kapasitas tinggi. Efisiensi tinggi dalam menangkap kotoran dengan penurunan tekanan rendah.',
                'photo'         => 'products/F90YD.webp',
            ],
            [
                'category_name' => 'Filter',
                'vendor_name'   => 'Fuzhou ARTHAS Fluid Equip.Tech',
                'code'          => 'F90TD',
                'name'          => 'Disc Filter T-type 130 micron 3", max.50m³/h',
                'description'   => 'Filter disc model T ukuran 3 inci debit jumbo (50 m³/jam). Ideal untuk pusat kontrol irigasi utama pabrik/perkebunan.',
                'photo'         => 'products/F90TD.webp',
            ],

            // --- SPRINKLER ---
            [
                'category_name' => 'Sprinkler',
                'vendor_name'   => 'Ningbo Shangda Plastic Hardware',
                'code'          => 'SD1634',
                'name'          => 'Sprinkler male ½", R=1,0-4,5m, max.180 LPH adjustable',
                'description'   => 'Sprinkler putar drat luar 1/2 inci. Radius siram 1 - 4.5 meter dengan debit air teratur hingga 180 liter/jam.',
                'photo'         => 'products/SD1634.webp',
            ],
            [
                'category_name' => 'Sprinkler',
                'vendor_name'   => 'Ningbo Shangda Plastic Hardware',
                'code'          => 'SD3042B',
                'name'          => 'Micro sprinkler 5-nozle, R=1,0-1,2m, max 40 LPH adjustable',
                'description'   => 'Sprinkler mikro pengabut 5 nozel untuk pendinginan greenhouse, budidaya jamur, dan bibit tanaman.',
                'photo'         => 'products/SD3042B.webp',
            ],
            [
                'category_name' => 'Sprinkler',
                'vendor_name'   => 'Ningbo Shangda Plastic Hardware',
                'code'          => 'SD1624A',
                'name'          => 'Sprinkler male ½", R=4,0-5,0m max. 800 LPH',
                'description'   => 'Sprinkler penyiraman taman dan sayuran dengan jangkauan radius hingga 5 meter. Material plastik impact tahan panas.',
                'photo'         => 'products/SD1624A.webp',
            ],
            [
                'category_name' => 'Sprinkler',
                'vendor_name'   => 'Ningbo Shangda Plastic Hardware',
                'code'          => 'SD1622',
                'name'          => 'Butterfly sprinkler male ½" , R=2,0-4,0m max.1000LPH',
                'description'   => 'Sprinkler kupu-kupu (butterfly) drat 1/2 inci. Menghasilkan sebaran bulir air halus menyerupai hujan alami.',
                'photo'         => 'products/SD1622.webp',
            ],
            [
                'category_name' => 'Sprinkler',
                'vendor_name'   => 'Ningbo Shangda Plastic Hardware',
                'code'          => 'SD1609',
                'name'          => 'Rotary sprinkler male ½" , R=6,0-8,0m max.650 LPH',
                'description'   => 'Sprinkler rotasi putar radius jauh (6-8 meter). Cocok untuk rumput lapangan, kebun buah, dan tanaman hortikultura.',
                'photo'         => 'products/SD1609.webp',
            ],
            [
                'category_name' => 'Sprinkler',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'MSPC0135T',
                'name'          => 'PC Microsprinkler, 35L/h, Green nozzle, OD 8 mm stake and 1/2" BSP Male thread',
                'description'   => 'Micro-sprinkler compensated (PC) debit stabil 35 liter/jam. Dilengkapi tiang pancang 8mm dan adaptor drat 1/2".',
                'photo'         => 'products/MSPC0135T.webp',
            ],

            // --- CONNECTOR ---
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'TO021715B',
                'name'          => 'Lock Ring Offtake Dn17*15',
                'description'   => 'Konektor pengunci ring dari pipa utama ke selang drip 17mm. Mencegah kebocoran sambungan pada tekanan sedang.',
                'photo'         => 'products/TO021715B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'BC021617B',
                'name'          => 'Barb Lock Ring Coupling Dn17*16',
                'description'   => 'Sambungan lurus barb-lock ring untuk menghubungkan pipa PE 16mm ke selang drip 17mm secara kuat.',
                'photo'         => 'products/BC021617B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'LC0217B',
                'name'          => 'Lock Ring Coupling Tape Dn17',
                'description'   => 'Sambungan lurus (straight coupling) khusus selang pita drip tape 17mm dengan ring pengunci putar.',
                'photo'         => 'products/LC0217B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'TP0317B',
                'name'          => 'Lock Ring Tape Plug  Dn17',
                'description'   => 'Penutup ujung (end plug) selang pita drip tape 17mm dengan pengunci ring anti-lepas.',
                'photo'         => 'products/TP0317B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'BC011617B',
                'name'          => 'Barb Coupling Tape Dn17*16',
                'description'   => 'Konektor barb penyambung selang drip 17mm dan pipa PE 16mm. Pemasangan cepat tanpa alat khusus.',
                'photo'         => 'products/BC011617B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'CT0317B',
                'name'          => 'Croco Offtake Lay Flat Dn17',
                'description'   => 'Konektor jepit (croco) untuk menyambung selang drip 17mm langsung dari induk selang pipih LayFlat.',
                'photo'         => 'products/CT0317B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'OV031715B',
                'name'          => 'Off take tape valve Dn17*15',
                'description'   => 'Stop keran kecil pembuka/penutup jalur selang drip tape 17mm dari pipa cabang utama.',
                'photo'         => 'products/OV031715B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'TO011715B',
                'name'          => 'Tape Offtake Dn17*15',
                'description'   => 'Konektor cabang sederhana percabangan pipa utama 15mm ke selang drip tape 17mm.',
                'photo'         => 'products/TO011715B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'LC0117B',
                'name'          => 'Lock Coupling Tape Dn17',
                'description'   => 'Sambungan perbaikan (repair coupling) jika terdapat selang pita drip tape 17mm yang bocor/robek.',
                'photo'         => 'products/LC0117B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'TP0117B',
                'name'          => 'Tape Plug Dn17',
                'description'   => 'Sumbat penutup pipa/selang drip tape 17mm pada akhir barisan tanaman.',
                'photo'         => 'products/TP0117B.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'OP011615',
                'name'          => 'Off take PE pipe Dn16*15',
                'description'   => 'Konektor percabangan dari pipa induk PVC/PE besar menuju pipa PE 16mm.',
                'photo'         => 'products/OP011615.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'MC011612',
                'name'          => 'Male Thread Connector PE Pipe Dn16*½',
                'description'   => 'Konektor drat luar 1/2 inci ke pipa PE 16mm. Digunakan memasang pipa ke keran/valve.',
                'photo'         => 'products/MC011612.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'OT0116',
                'name'          => 'Offtake Tee for PVC Pipe,Dn16',
                'description'   => 'Konektor Tee percabangan dua arah pipa PE 16mm dari satu titik lubang pipa PVC.',
                'photo'         => 'products/OT0116.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'TC0116',
                'name'          => 'Tee Connector PE pipe Dn16',
                'description'   => 'Sambungan cabang T (Tee) sama ukuran untuk membagi aliran pipa PE 16mm.',
                'photo'         => 'products/TC0116.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'EL0116',
                'name'          => 'End Line PE Pipe Dn16',
                'description'   => 'Penutup akhir jalur pipa PE 16mm berbentuk angka 8 (figure-8 end closure).',
                'photo'         => 'products/EL0116.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'HS0216',
                'name'          => 'Holddown Support, Dn16',
                'description'   => 'Pasak penancap tanah untuk memegang pipa PE 16mm agar tidak bergeser terkena angin/hewan.',
                'photo'         => 'products/HS0216.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'RR011613',
                'name'          => 'T-type Rubber grommet Dn16*13',
                'description'   => 'Karet seal grommet pelindung bocor untuk pemasangan konektor offtake pada pipa PVC.',
                'photo'         => 'products/RR011613.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => '794063',
                'name'          => 'End cap LayFlat 2"',
                'description'   => 'Penutup ujung selang induk terpal (LayFlat hose) ukuran 2 inci.',
                'photo'         => 'products/794063.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => '794090',
                'name'          => 'End cap LayFlat 3"',
                'description'   => 'Klem penutup ujung selang terpal fleksibel LayFlat ukuran 3 inci.',
                'photo'         => 'products/794090.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => '79209063',
                'name'          => 'Reducing Tee LayFlat 3"x2"x3"',
                'description'   => 'Fitting Tee reducer selang LayFlat dari 3 inci bercabang ke pipa 2 inci.',
                'photo'         => 'products/79209063.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => '7950903',
                'name'          => 'Female Thread adaptor LayFlat 3"',
                'description'   => 'Adaptor drat dalam (female) 3 inci untuk penyambungan selang LayFlat ke pompa/katup.',
                'photo'         => 'products/7950903.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => '7950632',
                'name'          => 'Female Thread adaptor LayFlat 2"',
                'description'   => 'Adaptor drat dalam 2 inci sambungan selang LayFlat fleksibel.',
                'photo'         => 'products/7950632.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => '7960903',
                'name'          => 'Male Thread adaptor LayFlat 3"',
                'description'   => 'Adaptor drat luar (male) 3 inci penyambung selang LayFlat ke pipa manifold PVC.',
                'photo'         => 'products/7960903.webp',
            ],
            [
                'category_name' => 'Connector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => '7960632',
                'name'          => 'Male Thread adaptor LayFlat 2"',
                'description'   => 'Adaptor drat luar 2 inci untuk sambungan pipa fleksibel LayFlat.',
                'photo'         => 'products/7960632.webp',
            ],

            // --- CONTROLLER ---
            [
                'category_name' => 'Controller',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => 'HY10469',
                'name'          => 'Multi zone controller, In 230V/35VA Out 24VAC / 0.8A, 4 - 11 station',
                'description'   => 'Timer pengatur waktu irigasi otomatis multi-zona (4 hingga 11 stasiun). Mengontrol jadwal siram solenoid valve secara bergantian.',
                'photo'         => 'products/HY10469.webp',
            ],

            // --- DRIPPER ---
            [
                'category_name' => 'Dripper',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'W21522B',
                'name'          => '2-way stake kit with White/Black PE,Long Dripper Stake, Dn5, 5133P',
                'description'   => 'Set penancap dripper 2 arah lengkap dengan selang mikro PE. Mengalirkan air presisi ke dua pot/polibag sekaligus.',
                'photo'         => 'products/W21522B.webp',
            ],
            [
                'category_name' => 'Dripper',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'PCT0104',
                'name'          => 'Pressure Compensationg Dripper ,Take Apart, 1/4", Black Color, 4/Lh@0.8-3.2bar, Dn5',
                'description'   => 'Emitter penetes tahan tekanan (Pressure Compensating) 4 liter/jam. Bisa dibuka-pasang untuk dibersihkan jika tersumbat.',
                'photo'         => 'products/PCT0104.webp',
            ],

            // --- DRIPLINE ---
            [
                'category_name' => 'Dripline',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'DT0116302014S',
                'name'          => 'DripTape 16mm*0.3mm*20cm*1.4LPH',
                'description'   => 'Selang pipih drip tape 16mm tebal 0.3mm jarak antar penetes 20cm (1.4 LPH). Cocok untuk cabai, bawang, dan sayuran baris.',
                'photo'         => 'products/DT0116302014S.webp',
            ],
            [
                'category_name' => 'Dripline',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'DT0116302014S',
                'name'          => 'DripTape 16mm*0.3mm*20cm*1.0LPH',
                'description'   => 'Selang irigasi tetes pipih 16mm jarak penetes 20cm debit hemat 1.0 liter/jam untuk efisiensi air maksimal.',
                'photo'         => 'products/DT0116302014S.webp',
            ],
            [
                'category_name' => 'Dripline',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'PCAS0116403020',
                'name'          => 'PC100 Pressure Compensating Driptape Anti-Siphon, Dn16*0.4mm*30cm*2.0L/H',
                'description'   => 'Pita drip kompensasi tekanan (PC) & Anti-Siphon. Mencegah kotoran terhisap saat air dimatikan pada lahan miring.',
                'photo'         => 'products/PCAS0116403020.webp',
            ],
            [
                'category_name' => 'Dripline',
                'vendor_name'   => 'ChinaDrip',
                'code'          => 'PCAS01161205020',
                'name'          => 'PC100 Pressure Compensating Dripline Anti-Siphon, Dn16*1.2mm*50cm*2.0L/H',
                'description'   => 'Selang dripline tebal (1.2mm) tahan pemakaian bertahun-tahun. Fitur Anti-Siphon dan jarak emiter 50cm untuk kebun buah/kopi.',
                'photo'         => 'products/PCAS01161205020.webp',
            ],

            // --- FERTILIZER INJECTOR ---
            [
                'category_name' => 'Fertilizer Injector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => 'HY2504',
                'name'          => 'Proportional Fertilizer Applicator, IN/OUT ¾" / 0,4-4,0% / 20-2500 LPH',
                'description'   => 'Dosing pump proporsional tanpa listrik. Otomatis menyedot dan mencampur pupuk cair sesuai proporsi rasio air.',
                'photo'         => 'products/HY2504.webp',
            ],
            [
                'category_name' => 'Fertilizer Injector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => 'F32V',
                'name'          => 'New Ventury Fertilizer Injector Ø 1" / 300LPH - max.8m³/h',
                'description'   => 'Injektor Venturi 1 inci memanfaatkan perbedaan tekanan air untuk menyedot pupuk cair ke jaringan irigasi.',
                'photo'         => 'products/F32V.webp',
            ],
            [
                'category_name' => 'Fertilizer Injector',
                'vendor_name'   => 'HYRT Irrigation',
                'code'          => 'F50V',
                'name'          => 'New Ventury Fertilizer Injector Ø 1-½" / 780LPH - max.15m³/h',
                'description'   => 'Injektor Venturi ukuran 1.5 inci kapasitas penyedotan pupuk tinggi (780 LPH) untuk fertigasi lahan luas.',
                'photo'         => 'products/F50V.webp',
            ],
        ];

        // 4. Simpan ke Database
        foreach ($productsData as $prod) {
            Product::create([
                'category_id' => $categories[$prod['category_name']] ?? null,
                'vendor_id'   => $vendors[$prod['vendor_name']] ?? null,
                'code'        => $prod['code'],
                'name'        => $prod['name'],
                'slug'        => Str::slug($prod['name'] . '-' . $prod['code'] . '-' . Str::random(4)),
                'description' => $prod['description'],
                'photo'       => $prod['photo'] ?? null,
            ]);
        }
    }
}